### ISSUE TITLE
小程序云开发CMS

### ISSUE THREAD

**Issue by saltbo** [saltbo/blog#22]
微信云开发的控制台是数据库类的，实际使用中还是需要自行开发一个cms后台。

采用headless-cms的思路开发一款为小程序云开发使用的headless-cms。

**Comment by LionTao** [comment]
外部应用访问云开发的资源需要使用云开发的HTTP API，这过程中一定需要使用token进行鉴权，而token每天有申请次数的限制，因此需要安全保存已申请的仍在有效期内的token，否则可能会发生单日token耗尽导致无法更新数据的问题

BTW，这个想法可以对接静态网站生成器如gatsby和gridsome

**Comment by saltbo** [comment]
是的，任何Headless-CMS都可以很方便的对接静态博客
